spanish_speaking_countries = [
    "Argentina",
    "Bolivia",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Equatorial Guinea",
    "Guatemala",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Puerto Rico",
    "Spain",
    "Uruguay",
    "Venezuela",
]

categorias = ["electronica", "ropa", "hogar", "deportes", "libros"]

nombres_por_categoria = {
    "electronica": [
        "Laptop",
        "Auriculares",
        "Smartphone",
        "Tablet",
        "Monitor",
        "Teclado",
        "Mouse",
        "Cámara",
        "Parlante",
        "Smartwatch",
    ],
    "ropa": [
        "Remera",
        "Pantalón",
        "Zapatillas",
        "Campera",
        "Vestido",
        "Shorts",
        "Medias",
        "Gorra",
        "Bufanda",
        "Chomba",
    ],
    "hogar": [
        "Silla",
        "Mesa",
        "Lámpara",
        "Almohada",
        "Sábanas",
        "Toalla",
        "Espejo",
        "Cuadro",
        "Florero",
        "Alfombra",
    ],
    "deportes": [
        "Pelota",
        "Raqueta",
        "Bicicleta",
        "Casco",
        "Guantes",
        "Mochila",
        "Botella",
        "Colchoneta",
        "Pesas",
        "Canilleras",
    ],
    "libros": [
        "Novela",
        "Diccionario",
        "Biografía",
        "Cómic",
        "Ensayo",
        "Poesía",
        "Thriller",
        "Ciencia Ficción",
        "Historia",
        "Autoayuda",
    ],
}

precios_por_categoria = {
    "electronica": (50, 1500),
    "ropa": (10, 200),
    "hogar": (15, 500),
    "deportes": (10, 100),
    "libros": (5, 50),
}
