spanish_speaking_countries = [
    "Argentina",
    "Bolivia",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Equatorial Guinea",
    "Guatemala",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Puerto Rico",
    "Spain",
    "Uruguay",
    "Venezuela",
]

categorias = ["electronica", "ropa", "hogar", "deportes", "libros"]

nombres_por_categoria = {
    "electronica": [
        "Laptop",
        "Auriculares",
        "Smartphone",
        "Tablet",
        "Monitor",
        "Teclado",
        "Mouse",
        "Cámara",
        "Parlante",
        "Smartwatch",
    ],
    "ropa": [
        "Remera",
        "Pantalón",
        "Zapatillas",
        "Campera",
        "Vestido",
        "Shorts",
        "Medias",
        "Gorra",
        "Bufanda",
        "Chomba",
    ],
    "hogar": [
        "Silla",
        "Mesa",
        "Lámpara",
        "Almohada",
        "Sábanas",
        "Toalla",
        "Espejo",
        "Cuadro",
        "Florero",
        "Alfombra",
    ],
    "deportes": [
        "Pelota",
        "Raqueta",
        "Bicicleta",
        "Casco",
        "Guantes",
        "Mochila",
        "Botella",
        "Colchoneta",
        "Pesas",
        "Canilleras",
    ],
    "libros": [
        "Novela",
        "Diccionario",
        "Biografía",
        "Cómic",
        "Ensayo",
        "Poesía",
        "Thriller",
        "Ciencia Ficción",
        "Historia",
        "Autoayuda",
    ],
}

precios_por_categoria = {
    "electronica": (50, 1500),
    "ropa": (10, 200),
    "hogar": (15, 500),
    "deportes": (10, 100),
    "libros": (5, 50),
}

paises_mapping = {
    "ESP": "Spain",
    "NIC": "Nicaragua",
}

ciudades_por_pais = {
    "Argentina": [
        "Buenos Aires",
        "Córdoba",
        "Rosario",
        "Mendoza",
        "Tucumán",
        "La Plata",
        "Mar del Plata",
        "Salta",
        "Santa Fe",
        "San Juan",
    ],
    "Bolivia": [
        "La Paz",
        "Santa Cruz",
        "Cochabamba",
        "Sucre",
        "Oruro",
        "Potosí",
        "Tarija",
        "Trinidad",
        "Cobija",
        "Riberalta",
    ],
    "Chile": [
        "Santiago",
        "Valparaíso",
        "Concepción",
        "La Serena",
        "Antofagasta",
        "Temuco",
        "Rancagua",
        "Talca",
        "Arica",
        "Iquique",
    ],
    "Colombia": [
        "Bogotá",
        "Medellín",
        "Cali",
        "Barranquilla",
        "Cartagena",
        "Cúcuta",
        "Bucaramanga",
        "Pereira",
        "Santa Marta",
        "Ibagué",
    ],
    "Costa Rica": [
        "San José",
        "Alajuela",
        "Cartago",
        "Heredia",
        "Liberia",
        "Pérez Zeledón",
        "San Carlos",
        "Puntarenas",
        "Limón",
        "Nicoya",
    ],
    "Cuba": [
        "La Habana",
        "Santiago de Cuba",
        "Camagüey",
        "Holguín",
        "Guantánamo",
        "Santa Clara",
        "Las Tunas",
        "Bayamo",
        "Cienfuegos",
        "Matanzas",
    ],
    "Dominican Republic": [
        "Santo Domingo",
        "Santiago",
        "La Romana",
        "San Pedro de Macorís",
        "San Francisco de Macorís",
        "La Vega",
        "Barahona",
        "Moca",
        "Puerto Plata",
        "Higüey",
    ],
    "Ecuador": [
        "Quito",
        "Guayaquil",
        "Cuenca",
        "Santo Domingo",
        "Machala",
        "Durán",
        "Manta",
        "Portoviejo",
        "Loja",
        "Ambato",
    ],
    "El Salvador": [
        "San Salvador",
        "Santa Ana",
        "San Miguel",
        "Soyapango",
        "Mejicanos",
        "Apopa",
        "Delgado",
        "Sonsonate",
        "Ahuachapán",
        "Usulután",
    ],
    "Equatorial Guinea": [
        "Malabo",
        "Bata",
        "Ebebiyín",
        "Aconibe",
        "Añisoc",
        "Luba",
        "Evinayong",
        "Mongomo",
        "Rebola",
        "Riaba",
    ],
    "Guatemala": [
        "Ciudad de Guatemala",
        "Mixco",
        "Villa Nueva",
        "Quetzaltenango",
        "Escuintla",
        "Villa Canales",
        "Chinautla",
        "Huehuetenango",
        "San Juan Sacatepéquez",
        "Jalapa",
    ],
    "Honduras": [
        "Tegucigalpa",
        "San Pedro Sula",
        "Choloma",
        "La Ceiba",
        "El Progreso",
        "Choluteca",
        "Comayagua",
        "Puerto Cortés",
        "Danlí",
        "Juticalpa",
    ],
    "Mexico": [
        "Ciudad de México",
        "Guadalajara",
        "Monterrey",
        "Puebla",
        "Tijuana",
        "León",
        "Juárez",
        "Zapopan",
        "Mérida",
        "Cancún",
    ],
    "Nicaragua": [
        "Managua",
        "León",
        "Masaya",
        "Matagalpa",
        "Chinandega",
        "Granada",
        "Estelí",
        "Tipitapa",
        "Ciudad Sandino",
        "Jinotega",
    ],
    "Panama": [
        "Ciudad de Panamá",
        "San Miguelito",
        "Tocumen",
        "David",
        "Arraiján",
        "Colón",
        "La Chorrera",
        "Penonomé",
        "Santiago",
        "Chitré",
    ],
    "Paraguay": [
        "Asunción",
        "Ciudad del Este",
        "San Lorenzo",
        "Luque",
        "Capiatá",
        "Lambaré",
        "Fernando de la Mora",
        "Limpio",
        "Ñemby",
        "Encarnación",
    ],
    "Peru": [
        "Lima",
        "Arequipa",
        "Trujillo",
        "Chiclayo",
        "Piura",
        "Iquitos",
        "Cusco",
        "Chimbote",
        "Huancayo",
        "Tacna",
    ],
    "Puerto Rico": [
        "San Juan",
        "Bayamón",
        "Carolina",
        "Ponce",
        "Caguas",
        "Guaynabo",
        "Arecibo",
        "Toa Baja",
        "Mayagüez",
        "Trujillo Alto",
    ],
    "Spain": [
        "Madrid",
        "Barcelona",
        "Valencia",
        "Sevilla",
        "Zaragoza",
        "Málaga",
        "Murcia",
        "Palma",
        "Las Palmas",
        "Bilbao",
    ],
    "Uruguay": [
        "Montevideo",
        "Salto",
        "Ciudad de la Costa",
        "Paysandú",
        "Las Piedras",
        "Rivera",
        "Maldonado",
        "Tacuarembó",
        "Melo",
        "Mercedes",
    ],
    "Venezuela": [
        "Caracas",
        "Maracaibo",
        "Valencia",
        "Barquisimeto",
        "Maracay",
        "Ciudad Guayana",
        "Barcelona",
        "Maturín",
        "Cumaná",
        "Petare",
    ],
}
